### ISSUE TITLE
Unable to get working on Edge 820 - IQ + Exclamation Mark displayed

### ISSUE THREAD

**Issue by benze** [house-of-abbey/GarminHomeAssistant#238]
I'm trying to install and configure HomeAssistant on my Edge 820 and have followed the documentation as closely as possible. However, when I try to open the app on the 820, I see the item name from the JSON flash quickly on the screen, then replaced with a giant IQ and exclamation mark.

The fact that I can see the item name from my JSON file tells me that it is capable to reading the public JSON from my HA instance. If I intentionally configure either the API endpoint or the API key incorrectly, I get a different error message (No JSON returned from HTTP request).

So my endpoint is correct, and API key is correct.

When I check the CIQ_LOG.YML file, I see the following error message:

```
---
Error: Unexpected Type Error
Details: 'Failed invoking <symbol>'
Time: 2025-05-07T01:34:13Z
Part-Number: 006-B2530-00
Firmware-Version: '12.70'
Language-Code: eng
ConnectIQ-Version: 5.1.1
Store-Id: 61c91d28-ec5e-438d-9f83-39e9f45b199d
Store-Version: 39
Filename: F5711440
Appname: HomeAssistant
Stack: 
  - pc: 0x10003390
```

I have tried multiple different configurations of the JSON file, but nothing seems to make a difference. For example:

```
{
  "$schema": "https://raw.githubusercontent.com/house-of-abbey/GarminHomeAssistant/main/config.schema.json",
  "title": "Home",
  "items": [
    {
      "entity": "light.ratgdov25i_0bd472_light",
      "name": "Bedroom Light",
      "type": "toggle"
    }
  ]
}
```

I have used the Web configurator and the toggle button works (I see the light go on and off).
I have also tried "tap", and even info types to no avail.

The same configuration works on a Garmin 265.

Is there a limitation on the Edge 820?

**Comment by philipabbey** [comment]
Thank you for this report. If the menu works on another Garmin device, that does suggest a bug. The absence of a required symbol in the debug log suggests an incompatibility. We have been relying on user reports to check those Edge devices work, you should see an entry in the app history to the effect, so I will look again.

**Comment by philipabbey** [comment]
@benze I was wondering if you had an update? Did you investigate or have you given up? Thanks.

**Comment by philipabbey** [comment]
Thank you for going to this effort.

I was wondering which settings you had enabled after the reinstall? Was it just the API key and two URLs? i.e. The minimum necessary to (supposedly) get the App working.

**Comment by benze** [comment]
I tried to install the widget version, but I cannot seem to get it to install.  I first uninstalled the application version then keep trying to install the widget but it does not install.  It shows as compatible in Garmin IQ, but when I try to sync the device the widget does not transfer.

I think my next step is to do a factory reset on the device and try again.

**Comment by philipabbey** [comment]
This is sounding bad. I wonder if the simulation  of the device is not true. As such, the remedy would be to exclude the device as there's no obvious means to diagnose the problem and discrepancy with simulation.

**Comment by philipabbey** [comment]
I've just had a similar problem on a different device. It may not be device type specific, but instead the software has somehow got into a state where the state includes the Garmin device on the Home Assistant end too.

**Comment by benze** [comment]
Thanks - found it under the Mobile App integration.  Was able to delete it from there.

Restarted the Edge 820, got the same behaviour as before; the app flashes for a second (I can see the toggle button) then quickly replaced with the IQ! logo.

> The fix for me was to turn off the background service, save settings, restart the app, then quit the app and turn the background service back on in the settings and restart the app.

Which background service are you stopping?  The default config in the Edge 820 config page (via Garmin Connect App) is to have background services disabled.  I tried to enable it, quit and restart the App on the 820, quit & then disable it (via Connect app),  restart the 820 app but no difference.

I tried to enable Mobile App debug logging in HA to see if I could see anything additional show up there, but stragely, I don't see any logs show up in HA Core for Mobile App at all.

**Comment by philipabbey** [comment]
So my application crash was at this line of code: https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/source/WebhookManager.mc#L181. I note the comments I left in:

```
// !! Speculative code for an application crash !!
// Webhook ID might have been deleted on Home Assistant server and a Lang.String is trying to tell us an error message
```

I'm still pondering that one, and wonder if its a different situation to yours.

I've been going through the code to check if any calls are made that are to more futuristic API levels that 3.1.0. I recall they are allowed but have to be tested for presence, and I wondered if I had failed to do so for your device.

Otherwise I'm still stuck looking for clues as to how to simulate the problem. A pre-requisite to being able to fix it. Sorry nothing more to go on presently.

**Comment by benze** [comment]
> Otherwise I'm still stuck looking for clues as to how to simulate the problem. A pre-requisite to being able to fix it. Sorry nothing more to go on presently.

I understand entirely; how are you able to simulate the different devices?  I looked for a Garmin emulator quickly and couldn't find anything.  Do you need a specific Garmin developer account to get access to it?  I am wondering if there is a way I can virtualize my device to replicate it in a dev environment.

**Comment by philipabbey** [comment]
> I looked for a Garmin emulator quickly and couldn't find anything.

See https://developer.garmin.com/connect-iq/overview/

**Comment by philipabbey** [comment]
I'm worried I will have to remove this device from the supported list if it really is behaving badly when another of your devices works. You will see from point (6) under https://github.com/house-of-abbey/GarminHomeAssistant?tab=readme-ov-file#known-issues that there are other known issues with Edge devices.

**Comment by philipabbey** [comment]
Just a thought, but the timing of the problem might indicate that the device has run out of [Timer](https://developer.garmin.com/connect-iq/api-docs/Toybox/Timer/Timer.html)s. I should be able to verify how many timers each device has, I think it was listed on https://developer.garmin.com/connect-iq/reference-guides/devices-reference/, but that page has gone missing within the last few weeks. This would not be an easy test to check without runtime logging on the target device.

**Comment by philipabbey** [comment]
It would mean side loading a version of the application customised for logging to a page on the web. Entirely insecure. A version I have not yet written. It's some significant effort.

**Comment by philipabbey** [comment]
> Just a thought, but the timing of the problem might indicate that the device has run out of [Timer](https://developer.garmin.com/connect-iq/api-docs/Toybox/Timer/Timer.html)s.

v3.0 has a more efficient use of Timers. I just wondered if that might have changed the behaviour of the application on Edge 820 devices.

**Comment by benze** [comment]
I'll give it a shot and get back to you.

**Comment by philipabbey** [comment]
@benze We have managed to find a couple of causes of crashing recently with the recent versions v3.x. Some of these ended in the "IQ!" screen. So I'm going to ask you to re-test with the latest version. We've also implemented a solution to a problem caused by device deletion on the HA server end. If the Webhook ID is out from the server, API calls will fail. See https://github.com/house-of-abbey/GarminHomeAssistant/blob/main/TroubleShooting.md#failed-api-calls.

So a few fixes and I'm hoping one of them solve your issue here.

**Comment by philipabbey** [comment]
@benze Any update?

**Comment by benze** [comment]
@philipabbey Sorry for the delay; have been moving so a bit crazy around here.  I did try the new version but sadly still the same issue. :(. Any type of additional debug logs that I can generate of use?

**Comment by poaudet** [comment]
Hi! I've got a similar error for a different context:

Vivoactive 5
Error happen when I tap on an entity that should show a picker

```json
{
  "$schema": "https://raw.githubusercontent.com/house-of-abbey/GarminHomeAssistant/main/config.schema.json",
  "title": "Home",
  "items": [
    {
      "entity": "light.lumiere_bureau",
      "name": "Bureau",
      "type": "toggle"
    },
    {
      "entity": "light.sous_sol",
      "name": "Sous-sol",
      "type": "toggle"
    },
    {
      "entity": "switch.prise_wifi",
      "name": "Cafetière",
      "type": "toggle"
    },
    {
      "name": "Chauffage",
      "content": "{{ ' %.1f' | format(state_attr('climate.thermostat','temperature')) }}",
      "type": "numeric",
      "entity": "climate.thermostat",
      "tap_action": {
        "action": "climate.set_temperature",
        "picker": {
          "step": 0.5,
          "start": 10,
          "stop": 30,
          "attribute": "temperature",
          "data_attribute": "temperature"
        }
      }
    }
  ]
}
```

The toggle entities are working as expected
The climate entity show the temperature state but when accessing the picker, I am getting the IQ! Icon.

The log provided me the exact error as the OP

**Comment by poaudet** [comment]
PR https://github.com/house-of-abbey/GarminHomeAssistant/pull/345#issue-4005525552
resolved on my side!

**Comment by philipabbey** [comment]
Your number picker suddenly started working?

**Comment by poaudet** [comment]
No sorry! I was not very clear !

I have made a PR. I refactor the number picker with Amazon Q and it works with my device and Venu2 on simulator

**Comment by philipabbey** [comment]
> In short, there was an invalid number of arguments (new version of the picker Api probably?)

I'm not seeing where the number of arguments has changed.
